# Generated by Django 4.0 on 2022-03-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksIssued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivery', models.DateField(null=True)),
                ('date_return', models.DateField(null=True)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.book')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=256, null=True, verbose_name='friend_name')),
                ('books', models.ManyToManyField(blank=True, null=True, through='p_library.BooksIssued', to='p_library.Book', verbose_name='friend_books')),
            ],
        ),
        migrations.AddField(
            model_name='booksissued',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.friend'),
        ),
    ]
