# Generated by Django 4.0 on 2022-04-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_booksissued_friend_booksissued_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksissued',
            name='date_return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(blank=True, through='p_library.BooksIssued', to='p_library.Book', verbose_name='friend_books'),
        ),
    ]
