# Generated by Django 4.0 on 2022-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_alter_booksissued_date_return_alter_friend_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='book_covers/%Y/%m/%d %H:%M:%S'),
        ),
    ]
